# Clean Oh My ZSH directory
- name: Install Oh My ZSH
  ansible.builtin.shell:
    cmd: rm -rf ~/.oh-my-zsh
  tags:
  - zsh

- name: Get the path to ZSH
  become: false
  local_action: command which zsh
  register: zsh_path
  tags:
  - zsh
  
- name: "Ensure homebrew zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  tags:
  - zsh
  
# Install Oh My ZSH Directory
- name: Install Oh My ZSH
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
  - zsh
  
# Install plugins
- name: Install zsh-autosuggestions
  ansible.builtin.shell:
    cmd: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  tags:
  - zsh
  
- name: Install zsh-syntax-highlighting
  ansible.builtin.shell:
    cmd: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  tags:
  - zsh
  
# Neovim Plugin manager
- name: Install neovim-plugin manager
  ansible.builtin.shell:
    cmd: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  tags:
  - zsh
  
# Need these fonts for showing some of the weird sign characters on terminal
- name: Install fonts
  shell: |
    git clone https://github.com/powerline/fonts.git --depth=1
    ./fonts/install.sh
    rm -rf fonts
  tags:
  - zsh
  

# Download get_iplayer
# https://github.com/get-iplayer/get_iplayer/wiki/guide-tv
- name: Download get_iplayer file with checksum url (sha256)
  ansible.builtin.get_url:
    url: https://github.com/get-iplayer/get_iplayer_macos/releases/download/3.30.0/get_iplayer-3.30.0-macos-x64.pkg
    dest: /Users/sasson/Downloads/get_iplayer-3.30.0-macos-x64.pkg
    checksum: sha256:https://github.com/get-iplayer/get_iplayer_macos/releases/download/3.30.0/get_iplayer-3.30.0-macos-x64.pkg.sha256
  tags:
  - iplayer

- name: Changing perm of get_iplayer-3.30.0-macos-x64.pkg, adding "+x"
  file: dest=/Users/sasson/Downloads/get_iplayer-3.30.0-macos-x64.pkg mode=a+x
  tags:
  - iplayer

